# JSP配置 tab == >  空格  禁止使用tab
spring:
   mvc:
      view:
         prefix:WEB-INF/jsp
         suffix：.jsp
                
    # 数据库        
   datasourse:
      url:jdbc:mysql://127.0.0.1/test
      username=root
      password=aaaaaaaa
      driver-class-name=com.mysql.jdbc.Driver

          
                