package com.yc.blog.dao;

import com.yc.blog.bean.Article;
import com.yc.blog.bean.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @SelectProvider(type=ArticleSqlProvider.class, method="countByExample")
    long countByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @DeleteProvider(type=ArticleSqlProvider.class, method="deleteByExample")
    int deleteByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @Delete({
        "delete from article",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @Insert({
        "insert into article (author, title, ",
        "keyWords, description, ",
        "categoryId, label, ",
        "titleImgs, status, ",
        "createTime, readCnt, ",
        "agreeCnt, commCnt, ",
        "content)",
        "values (#{author,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{keywords,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{categoryid,jdbcType=INTEGER}, #{label,jdbcType=VARCHAR}, ",
        "#{titleimgs,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{createtime,jdbcType=TIMESTAMP}, #{readcnt,jdbcType=INTEGER}, ",
        "#{agreecnt,jdbcType=INTEGER}, #{commcnt,jdbcType=INTEGER}, ",
        "#{content,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @InsertProvider(type=ArticleSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @SelectProvider(type=ArticleSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="keyWords", property="keywords", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="categoryId", property="categoryid", jdbcType=JdbcType.INTEGER),
        @Result(column="label", property="label", jdbcType=JdbcType.VARCHAR),
        @Result(column="titleImgs", property="titleimgs", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="readCnt", property="readcnt", jdbcType=JdbcType.INTEGER),
        @Result(column="agreeCnt", property="agreecnt", jdbcType=JdbcType.INTEGER),
        @Result(column="commCnt", property="commcnt", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Article> selectByExampleWithBLOBs(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @SelectProvider(type=ArticleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="keyWords", property="keywords", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="categoryId", property="categoryid", jdbcType=JdbcType.INTEGER),
        @Result(column="label", property="label", jdbcType=JdbcType.VARCHAR),
        @Result(column="titleImgs", property="titleimgs", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="readCnt", property="readcnt", jdbcType=JdbcType.INTEGER),
        @Result(column="agreeCnt", property="agreecnt", jdbcType=JdbcType.INTEGER),
        @Result(column="commCnt", property="commcnt", jdbcType=JdbcType.INTEGER)
    })
    List<Article> selectByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @Select({
        "select",
        "id, author, title, keyWords, description, categoryId, label, titleImgs, status, ",
        "createTime, readCnt, agreeCnt, commCnt, content",
        "from article",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="keyWords", property="keywords", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="categoryId", property="categoryid", jdbcType=JdbcType.INTEGER),
        @Result(column="label", property="label", jdbcType=JdbcType.VARCHAR),
        @Result(column="titleImgs", property="titleimgs", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="readCnt", property="readcnt", jdbcType=JdbcType.INTEGER),
        @Result(column="agreeCnt", property="agreecnt", jdbcType=JdbcType.INTEGER),
        @Result(column="commCnt", property="commcnt", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.LONGVARCHAR)
    })
    Article selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @UpdateProvider(type=ArticleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @UpdateProvider(type=ArticleSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @UpdateProvider(type=ArticleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @UpdateProvider(type=ArticleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @Update({
        "update article",
        "set author = #{author,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "keyWords = #{keywords,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "categoryId = #{categoryid,jdbcType=INTEGER},",
          "label = #{label,jdbcType=VARCHAR},",
          "titleImgs = #{titleimgs,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "createTime = #{createtime,jdbcType=TIMESTAMP},",
          "readCnt = #{readcnt,jdbcType=INTEGER},",
          "agreeCnt = #{agreecnt,jdbcType=INTEGER},",
          "commCnt = #{commcnt,jdbcType=INTEGER},",
          "content = #{content,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    @Update({
        "update article",
        "set author = #{author,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "keyWords = #{keywords,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "categoryId = #{categoryid,jdbcType=INTEGER},",
          "label = #{label,jdbcType=VARCHAR},",
          "titleImgs = #{titleimgs,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "createTime = #{createtime,jdbcType=TIMESTAMP},",
          "readCnt = #{readcnt,jdbcType=INTEGER},",
          "agreeCnt = #{agreecnt,jdbcType=INTEGER},",
          "commCnt = #{commcnt,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Article record);
}