package com.yc.blog.dao;

import com.yc.blog.bean.Article;
import com.yc.blog.bean.ArticleExample.Criteria;
import com.yc.blog.bean.ArticleExample.Criterion;
import com.yc.blog.bean.ArticleExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ArticleSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    public String countByExample(ArticleExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("article");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    public String deleteByExample(ArticleExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("article");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    public String insertSelective(Article record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("article");
        
        if (record.getAuthor() != null) {
            sql.VALUES("author", "#{author,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getKeywords() != null) {
            sql.VALUES("keyWords", "#{keywords,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=VARCHAR}");
        }
        
        if (record.getCategoryid() != null) {
            sql.VALUES("categoryId", "#{categoryid,jdbcType=INTEGER}");
        }
        
        if (record.getLabel() != null) {
            sql.VALUES("label", "#{label,jdbcType=VARCHAR}");
        }
        
        if (record.getTitleimgs() != null) {
            sql.VALUES("titleImgs", "#{titleimgs,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.VALUES("createTime", "#{createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReadcnt() != null) {
            sql.VALUES("readCnt", "#{readcnt,jdbcType=INTEGER}");
        }
        
        if (record.getAgreecnt() != null) {
            sql.VALUES("agreeCnt", "#{agreecnt,jdbcType=INTEGER}");
        }
        
        if (record.getCommcnt() != null) {
            sql.VALUES("commCnt", "#{commcnt,jdbcType=INTEGER}");
        }
        
        if (record.getContent() != null) {
            sql.VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    public String selectByExampleWithBLOBs(ArticleExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("author");
        sql.SELECT("title");
        sql.SELECT("keyWords");
        sql.SELECT("description");
        sql.SELECT("categoryId");
        sql.SELECT("label");
        sql.SELECT("titleImgs");
        sql.SELECT("status");
        sql.SELECT("createTime");
        sql.SELECT("readCnt");
        sql.SELECT("agreeCnt");
        sql.SELECT("commCnt");
        sql.SELECT("content");
        sql.FROM("article");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    public String selectByExample(ArticleExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("author");
        sql.SELECT("title");
        sql.SELECT("keyWords");
        sql.SELECT("description");
        sql.SELECT("categoryId");
        sql.SELECT("label");
        sql.SELECT("titleImgs");
        sql.SELECT("status");
        sql.SELECT("createTime");
        sql.SELECT("readCnt");
        sql.SELECT("agreeCnt");
        sql.SELECT("commCnt");
        sql.FROM("article");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Article record = (Article) parameter.get("record");
        ArticleExample example = (ArticleExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("article");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getAuthor() != null) {
            sql.SET("author = #{record.author,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getKeywords() != null) {
            sql.SET("keyWords = #{record.keywords,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        }
        
        if (record.getCategoryid() != null) {
            sql.SET("categoryId = #{record.categoryid,jdbcType=INTEGER}");
        }
        
        if (record.getLabel() != null) {
            sql.SET("label = #{record.label,jdbcType=VARCHAR}");
        }
        
        if (record.getTitleimgs() != null) {
            sql.SET("titleImgs = #{record.titleimgs,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("createTime = #{record.createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReadcnt() != null) {
            sql.SET("readCnt = #{record.readcnt,jdbcType=INTEGER}");
        }
        
        if (record.getAgreecnt() != null) {
            sql.SET("agreeCnt = #{record.agreecnt,jdbcType=INTEGER}");
        }
        
        if (record.getCommcnt() != null) {
            sql.SET("commCnt = #{record.commcnt,jdbcType=INTEGER}");
        }
        
        if (record.getContent() != null) {
            sql.SET("content = #{record.content,jdbcType=LONGVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("article");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("author = #{record.author,jdbcType=VARCHAR}");
        sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        sql.SET("keyWords = #{record.keywords,jdbcType=VARCHAR}");
        sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        sql.SET("categoryId = #{record.categoryid,jdbcType=INTEGER}");
        sql.SET("label = #{record.label,jdbcType=VARCHAR}");
        sql.SET("titleImgs = #{record.titleimgs,jdbcType=VARCHAR}");
        sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        sql.SET("createTime = #{record.createtime,jdbcType=TIMESTAMP}");
        sql.SET("readCnt = #{record.readcnt,jdbcType=INTEGER}");
        sql.SET("agreeCnt = #{record.agreecnt,jdbcType=INTEGER}");
        sql.SET("commCnt = #{record.commcnt,jdbcType=INTEGER}");
        sql.SET("content = #{record.content,jdbcType=LONGVARCHAR}");
        
        ArticleExample example = (ArticleExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("article");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("author = #{record.author,jdbcType=VARCHAR}");
        sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        sql.SET("keyWords = #{record.keywords,jdbcType=VARCHAR}");
        sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        sql.SET("categoryId = #{record.categoryid,jdbcType=INTEGER}");
        sql.SET("label = #{record.label,jdbcType=VARCHAR}");
        sql.SET("titleImgs = #{record.titleimgs,jdbcType=VARCHAR}");
        sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        sql.SET("createTime = #{record.createtime,jdbcType=TIMESTAMP}");
        sql.SET("readCnt = #{record.readcnt,jdbcType=INTEGER}");
        sql.SET("agreeCnt = #{record.agreecnt,jdbcType=INTEGER}");
        sql.SET("commCnt = #{record.commcnt,jdbcType=INTEGER}");
        
        ArticleExample example = (ArticleExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    public String updateByPrimaryKeySelective(Article record) {
        SQL sql = new SQL();
        sql.UPDATE("article");
        
        if (record.getAuthor() != null) {
            sql.SET("author = #{author,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getKeywords() != null) {
            sql.SET("keyWords = #{keywords,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=VARCHAR}");
        }
        
        if (record.getCategoryid() != null) {
            sql.SET("categoryId = #{categoryid,jdbcType=INTEGER}");
        }
        
        if (record.getLabel() != null) {
            sql.SET("label = #{label,jdbcType=VARCHAR}");
        }
        
        if (record.getTitleimgs() != null) {
            sql.SET("titleImgs = #{titleimgs,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("createTime = #{createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReadcnt() != null) {
            sql.SET("readCnt = #{readcnt,jdbcType=INTEGER}");
        }
        
        if (record.getAgreecnt() != null) {
            sql.SET("agreeCnt = #{agreecnt,jdbcType=INTEGER}");
        }
        
        if (record.getCommcnt() != null) {
            sql.SET("commCnt = #{commcnt,jdbcType=INTEGER}");
        }
        
        if (record.getContent() != null) {
            sql.SET("content = #{content,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Aug 14 20:21:19 CST 2019
     */
    protected void applyWhere(SQL sql, ArticleExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}